service: ami

frameworkVersion: ">=1.10.0 <2.0.0"

plugins:
  - serverless-webpack

custom:
  ami:
    AMI_AWS_REGION: 'us-east-1'
    AMI_RETENTION_PERIOD: '7'
    AMI_INVOCATION_SCHEDULE: 'cron(0 0 * * ? *)'
    
provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:provider.environment.AMI_AWS_REGION}
  environment:
    AMI_AWS_REGION: ${env:AMI_AWS_REGION, self:custom.ami.AMI_AWS_REGION}
    AMI_RETENTION_PERIOD: ${env:AMI_RETENTION_PERIOD, self:custom.ami.AMI_RETENTION_PERIOD}
    AMI_INVOCATION_SCHEDULE: ${env:AMI_INVOCATION_SCHEDULE, self:custom.ami.AMI_INVOCATION_SCHEDULE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeInstances
        - ec2:CreateImage
        - ec2:CreateTags
        - ec2:DescribeImages
        - ec2:DeregisterImage
        - ec2:DeleteSnapshot
      Resource: "*"

functions:
  createAMI:
    handler: handler.createAMI

  deleteAMI:
    handler: handler.deleteAMI

  createAndDeleteAMI:
    handler: handler.createAndDeleteAMI
    events:
      - schedule:
          rate: ${self:provider.environment.AMI_INVOCATION_SCHEDULE}
          enabled: true
