service: ami

frameworkVersion: ">=1.10.0 <2.0.0"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:provider.environment.AWS_REGION}
  environment:
    AWS_REGION: ${env:AWS_REGION, file(./constants.js):constants.AWS_REGION, 'us-east-1'}
    AMI_RETENTION_PERIOD: ${env:AMI_RETENTION_PERIOD, file(./constants.js):constants.AMI_RETENTION_PERIOD, '7'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeInstances
        - ec2:CreateImage
        - ec2:CreateTags
        - ec2:DescribeImages
        - ec2:DeregisterImage
        - ec2:DeleteSnapshot
      Resource: "*"

functions:
  createAMI:
    handler: handler.createAMI

  deleteAMI:
    handler: handler.deleteAMI

  createAndDeleteAMI:
    handler: handler.createAndDeleteAMI
    events:
      - schedule: ${env:INVOCATION_SCHEDULE, file(./constants.js):constants.INVOCATION_SCHEDULE, 'cron(0 0 * * ? *)'}
